### ISSUE TITLE
Inserir no README Informações sobre a disciplina

### ISSUE THREAD

**Issue by jorgehclinhares** [IF977/BikeGuide#1]
Adicionem a seguinte informação ao README de vocês: 

Projeto didático-prático da disciplina (IF977) Engenharia de Software, do curso de graduação em Sistemas de Informação do Centro de Informática (CIn) da Universidade Federal de Pernambuco (UFPE)

**Comment by bernardomelo** [comment]
Done

**Comment by SandrineMartins** [comment]
@bernardomelo Coloca essa informação em baixo do nome do projeto

**Comment by SandrineMartins** [comment]
@bernardomelo

**Comment by bernardomelo** [comment]
@SandrineMartins  done. Por favor, dá uma checada e um feedback caso tudo esteja ok - ou não.

**Comment by SandrineMartins** [comment]
Agora sim! Só cuidado no português "vim" não é a forma correta de escrita
