### ISSUE TITLE
Troca sqlite3 por postgresql

### ISSUE THREAD

**Issue by bernardomelo** [IF977/BikeGuide#13]
Bom dia,

Migramos o db de sqlite3 pra postgresql e conseguimos testar algumas coisas do login API google. Como decidimos trocar o método de login, pois estava bugando demais o API, tivemos que mudar umas coisas no db começou a bugar. Vocês poderiam ajudar-nos com a configuração do bd em postgresql, por favor?
Procurei muito no stackoverflow, já alterei direitinho o db.yml, porém continuando dando uns erros bizarros, como, por exemplo, 'fe_sendauth: no password supplied'.

Grato desde já.

**Comment by SandrineMartins** [comment]
Só pra esclarecer: 
vocês conseguiram fazer a migração correta e só depois começou a dar erro, certo?

Coloca aqui os prints dos erros, pra gente ter uma noção maior do que ta dando.

**Comment by bernardomelo** [comment]
@SandrineMartins ,
Isso, tinhamos conseguido migrar, mas na integração do Login começou a dar problema. 
Falei aqui com Ian, também monitor, e ele me disse que era melhor deixar o sqlite3 mesmo no c9 e migrar automaticamente através do próprio Heroku. 

Foi o que fizemos, retornamos pro sqlite3 e estamos trabalhando com ele mesmo.

Desculpe a demora da resposta, passei o final de semana sem tempo nenhum.
