### ISSUE TITLE
Bug no button_to "Login"

### ISSUE THREAD

**Issue by bernardomelo** [IF977/BikeGuide#15]
Bom dia,

Acabei de integrar a autenticação de usuário via Sorcery (uma gem para tal). Quando clico no botão de login na página home(Foto 1) (feito no html mesmo via helper 'button_to, users_path'), ele redireciona para uma url /users estranha(Foto2), onde possui um botão 'back' que, se clicado, lhe direciona para a página /users real(Foto3).

O que estaria causando isso? Os erros estranhos que aparecem na Foto 2 estão relacionados a um .require() na controller que, se eu boto, buga tudo.
![login1](https://cloud.githubusercontent.com/assets/20033283/26787382/32fbc0c6-49e0-11e7-889b-98b1b04bb276.png)
![login2](https://cloud.githubusercontent.com/assets/20033283/26787383/32fc9c76-49e0-11e7-83e4-405fb341997d.png)
![login3](https://cloud.githubusercontent.com/assets/20033283/26787384/32ffba28-49e0-11e7-9132-a36779615174.png)

**Comment by jorgehclinhares** [comment]
Eu tenho que ver a nível de implementação, podemos marcar uma reunião para dar uma olhadinha nisso

**Comment by bernardomelo** [comment]
@jorgehclinhares Certo, irei tentar ver isso hoje de tarde com @thiagoguimaraeso, se não conseguirmos arrumar, marcaremos.

**Comment by vinicius3w** [comment]
Verifica as rotas. O helper pode estar direcionando pra essa URI

Em 5 de jun de 2017 11:58 AM, "Bernardo Gomes de Melo" <
notifications@github.com> escreveu:

**Comment by bernardomelo** [comment]
@jorgehclinhares @vinicius3w Obrigado pelas dicas, galera. Dei uma checada nas rotas e também não era esse o problema, acabou que mudamos de button_to para link_to e se resolveu, devia ser algum bug no próprio helper.
