### ISSUE TITLE
Uso das labels

### ISSUE THREAD

**Issue by jorgehclinhares** [IF977/BikeGuide#2]
Acredito que foi passado na monitoria de github mas só reforçando o cadastramento e uso das Labels, em caso de dúvidas é só falar. Lembrando que a nomenclatura e as suas respectivas cores devem ser respeitadas.

![captura de tela 2017-04-19 as 08 43 15](https://cloud.githubusercontent.com/assets/11631238/25178510/6cf291b6-24dc-11e7-9cb2-a325c1979945.png)

https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by jorgehclinhares** [comment]
Vocês não implementaram o uso das labels.

**Comment by bernardomelo** [comment]
![screenshot from 2017-05-10 10-53-08](https://cloud.githubusercontent.com/assets/20033283/25902121/02316ba6-356f-11e7-9252-d415fcecb2aa.png)

Label implementadas, segue screenshot em anexo para verificação. Caso tenha problemas nelas, favor reabrir. Obrigado.

**Comment by SandrineMartins** [comment]
Vocês tem que cadastrar as labels que estão na imagem que Jorge mandou
