### ISSUE TITLE
Bug no up para o Heroku

### ISSUE THREAD

**Issue by bernardomelo** [IF977/BikeGuide#23]
Bom dia,

Upamos nossa aplicação pro Heroku. O push da master pro heroku foi tudo ok, mas quando abrimos o Heroku, ele aponta erro e não roda o site. 

"                        Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details."

No log, o erro apontado é: "at=error code=H10 desc="App crashed" method=GET path="/" host=bike-guide.herokuapp.com"
Tentamos de tudo para concertar, mas até agora estamos apanhando. Vocês teriam ideia do que está causando esse erro?

**Comment by jorgehclinhares** [comment]
O bug ainda persiste? pude ver que o app está online...
