### ISSUE TITLE
FeedBack sobre o Postmortem

### ISSUE THREAD

**Issue by lsca** [IF977/BikeGuide#6]
Tudo certinho, porém, algo me deixou em duvida e gostaria de saber se eu entendi corretamente para fechar a avaliação de vocês.

Planejado : 
Pesquisar API google maps.
**Implementar no site**

Feito :
Pesquisar API google maps.
**Implementar no site.**

O que não foi feito :

**Implementação do API google maps.**

Implementaram ou não?

**Comment by gabyalmirante** [comment]
Implementar no site ficou um pouco vago, mas queríamos dizer "Implementar algo no site", como por exemplo, a página inicial pura.

**Comment by bernardomelo** [comment]
Resolvido com Lucas.
