### ISSUE TITLE
Cadastrar HU's

### ISSUE THREAD

**Issue by pedrojsn96** [IF977/BikeGuide#8]
Vocês precisam cadastrar as HU's no início da iteração e não no final.
Lembrando que é necessário o uso de label e milestone.

**Comment by thiagoguimaraeso** [comment]
Certo Pedro. Está muito vago o suporte de vocês sobre a parte documental do projeto, por isso nem sabiamos desse detalhe. A ajuda totalmente remota claramente não está funcionando, gostaria que quando algum de vocês tiver disponibilidade, se reunir presencialmente no CIn essa semana ou na próxima pra explicar pra algum membro da equipe todas esses detalhes do processo documentativo.

**Comment by pedrojsn96** [comment]
Cara, toda parte documental está no git: https://github.com/IF977/monitoria-if977-SI

Sobre label e milestone creio que na monitoria de Git foi discutido isso.

**Comment by thiagoguimaraeso** [comment]
Certo, então que fique registrado aqui que permanecemos sem o apoio dos monitores da cadeira, por isso estamos recebendo apoio do aluno Lucas Glasner que está fazendo papel de nosso monitor. Abs.

**Comment by pedrojsn96** [comment]
Tiveram monitoria de Git, ambiente de dev, Rails, Cucumber, TDD, etc. 
Agora só falta monitoria de escrever documentação. 
Boa sorte.

**Comment by vinicius3w** [comment]
Thiago por favor, seja específico no que você espera e do que você chama de
falta de apoio.




--
*Vinicius Cardoso Garcia*
[www: vinicius3w.com]-[arxiv: http://arxiv.org/a/garcia_v_1]-[twitter:
@vinicius3w <http://www.twitter.com/vinicius3w>]


*Wyrd biõ fui arccd.*

**Comment by vinicius3w** [comment]
Nas aulas em classe, falei sobre o projeto e o modus operandi do projeto,
talvez você não estivesse presente, ou talvez tenha sido depois de você ter
ido embora mais cedo (o que, convenhamos, é usual né?).

Adicionalmente, na monitoria sobre o repositório - plataforma principal ao
redor do qual o projeto é executado - foram tratados estes pontos sobre
gerenciamento por issues, ciclo de vida das issues, geração de labels e
milestones.

Sobre a ciração das HUs, bem, isso foi visto em aula, comigo. Isso é
processo de desenvolvimento e se você parar para refletir um pouco, chegará
a conclusão que primeiro você entende, especifica e detalha o que vai fazer
e só depois começa a fazer. Se for para fazer de qualquer jeito e somente
depois ir especificar o que foi feito, bem pra isso não precisamos de
processo, correto?

Seja como for, mantendo a minha pergunta sobre o que exatamente vocês
esperam para que possamos alinhas as expectativas.

Abraços,



--
*Vinicius Cardoso Garcia*
[www: vinicius3w.com]-[arxiv: http://arxiv.org/a/garcia_v_1]-[twitter:
@vinicius3w <http://www.twitter.com/vinicius3w>]


*Wyrd biõ fui arccd.*

**Comment by thiagoguimaraeso** [comment]
Certo Professor, nossa equipe entendeu como funciona o cadastro das HU's e qual o sentido delas serem cadastradas no início de cada iteração, pelo simples fato de que é nelas que estaremos trabalhando. O não cadastro delas no começo dessa iteração foi descuido nosso, apesar de estarmos trabalhando baseado nelas, não atentamos a cadastrá-las como Issue aqui no git. O que nós esperavamos não do Sr., mas de nossos monitores, aqueles que foram designados a "acompanhar" nossa equipe, era apoio, e não somente cobrança.

Abs,

**Comment by jorgehclinhares** [comment]
Primeiro, eu não estou entendendo qual o motivo de tanta reclamação, principalmente de uma equipe que demorou 1 iteração para entrar em contato conosco via slack.  Se fossemos tão importante talvez vocês teriam entrado em contato antes. Enfim, lembrando que não somos mãe e pai de ninguém, todo mundo aqui é maior de idade e deveria compreender suas obrigações. O trabalho de monitoria é em sua totalidade consultivo, ou então eu que entendi errado, se vocês não entram em contato conosco não tem como saber quais suas necessidades. 

Segundo, todas as atividades foram devidamente listadas e especificadas no site/monitorias, sendo assim, nós monitores entendemos que vocês tem conhecimento sobre as entregas. Em nenhum momento, você @thiagoguimaraeso ou qualquer outra pessoa da sua equipe chegou para mim ou para @SandrineMartins para ressalva sobre nossa assistência, o que eu já acho uma total falta de respeito. Mas tudo bem, esse é um ambiente para tentarmos solucionar o problema, então vamos trabalhar nele. Pode deixar 👍

**Comment by SandrineMartins** [comment]
Então, há 7 dias eu abri uma issue aqui informando a equipe que as HU's precisavam ser cadastras no início da iteração e não ao fim da mesma, o que dava tempo para a equipe fazer esta atividade antes do fim da iteração. Há 19 dias @jorgehclinhares abriu uma issue para informar sobre o uso de labels e reforçou que esse assunto havia sido passado na monitoria.
Até então a equipe não havia cadastrado as HU's como issues o que deixa difícil pro monitor adivinhar que a equipe estava com dúvidas quanto o uso das mesmas.
Ainda sobre o "não apoio" dos monitores, não é nossa obrigação avisar a equipe que falta documentação para ser entregue e ainda assim eu o fiz na i0 para que a equipe não zerasse uma nota.
Por fim gostaria de ressaltar a pergunta de @vinicius3w  sobre o que você espera e do que você chama de falta de apoio.

**Comment by bernardomelo** [comment]
Não quero entrar em toda essa confusão - inclusive peço perdão diante de
qualquer desentendimento -, mas a questão do uso das labels não foi passado
claramente na monitoria de Git. O que a monitora passou foi comandos
básicos do mesmo e sobre issues e as labels ela apenas citou que teríamos
que criar e falou algo como "são bastante importantes", só.

Ademais, admito nosso erro em relação as issues e uso de labels, se não me
engano, algum de vocês tinha passado um "cheat sheet" ou um guia sobre
tais, correto? Poderiam fornecer novamente?

Em 25 de mai de 2017 12:30 PM, "Sandrine" <notifications@github.com>
escreveu:

**Comment by vinicius3w** [comment]
certo, esse é o tipo de coisa que temos que identificar. mas existe uma
distância entre não ter apoio e não ter entendido corretamente alguma coisa.

vamos trabalhar em cima da solução e não ficar em cima do problema.

agora, uma expectativa que temos que alinhar, e eu deixei isso muito claro
na sala, é no tocante a participação dos monitores no projeto. eles possuem
dois papéis: 1º) consultivo, estão disponíveis para consulta, tirar
dúvidas, esclarecer coisas, etc (neste ponto, ao não entender a função das
labels, vocês deveriam ter ido atrás), e 2º) acompanhamento avaliativo,
para segundo as normas estabelecidas pela entidade máxima de avaliação da
disciplina (eu), irem mensurando o andamento e desempenho de vocês.

desta forma, conforme eu já falei também, meu conselho para vocês é mudar a
postura. vocês estão muito passivos, aguardando que os monitores, por
exemplo, digam o que está errado ou não feito (e eles até fizeram isso, tá
registrado), e passem a ter uma postura mais pró-ativa. vão atrás, se
movimentem. se vocês não correrem atrás, não vai dar certo.

faz parte da estratégia de aprendizagem o conhecimento ser passado de forma
incompleta para vocês traçarem [arte do caminho pelas próprias pernas.

vamos em frente!



--
*Vinicius Cardoso Garcia*
[www: vinicius3w.com]-[arxiv: http://arxiv.org/a/garcia_v_1]-[twitter:
@vinicius3w <http://www.twitter.com/vinicius3w>]


*Wyrd biõ fui arccd.*

2017-05-25 13:35 GMT-03:00 Bernardo Gomes de Melo <notifications@github.com>
:

**Comment by SandrineMartins** [comment]
Creio que seja este para a criação de labels https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

e para milestones
https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/

As labels vocês criaram, mas como não cadastraram issues não usaram label aguma.
Sobre como usar cada uma segue slide da monitoria
![github](https://cloud.githubusercontent.com/assets/7128232/26461166/93dd563e-4152-11e7-8a83-cca9dc673565.png)

**Comment by bernardomelo** [comment]
Agradecido 👍

Em 25 de mai de 2017 2:01 PM, "Sandrine" <notifications@github.com>
escreveu:
